spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: SpringBootDocker
  datasource:
    username: ${MYSQL_USER:#{user}}
    password: ${MYSQL_PASSWORD:#{password}}
    url: ${MYSQL_URL}
  jpa:
    show-sql: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
