spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: SpringBootDocker
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_LOCAL_PORT}
      username: ${MONGO_INITDB_ROOT_USERNAME:#{user}}
      password: ${MONGO_INITDB_ROOT_PASSWORD:#{password}}
      database: ${MONGO_DB_NAME}