version: '3.3'
services:
  mongodb:
    image: mongo:7.0.6
    env_file: .env
    ports:
      - '${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}'
    volumes:
      - ./src/main/resources/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db
volumes:
  mongodb_data: