version: '3.3'
services:
  mongodb:
    image: mongo:7.0.6
    env_file: .env
    ports:
      - '${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}'
    volumes:
      - mongodb-data:/data/db
      - ./src/main/resources/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  app:
    container_name: spring
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
    depends_on:
      mongodb:
        condition: service_healthy
volumes:
  mongodb-data: