version: '3.3'

services:
    mssql:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2017-latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "pAssworD4321"
        ports:
            - "1433:1433"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mounting SQL script for initialization
            - mssql_data:/var/opt/mssql
        networks:
            - mssql_network

networks:
  mssql_network:

volumes:
  mssql_data: