version: '3.3'

services:
    mssql:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "pAssworD4321"
        ports:
            - "1433:1433"
        volumes:
            - mssql_data:/var/opt/mssql
volumes:
    mssql_data: